### ISSUE TITLE
Execution is too slow

### ISSUE THREAD

**Issue by shiva4983** [healenium/healenium-web#104]
Hi Team,

Post 3.1 update, I am noticing considerable slowness in script execution. To give a perspective with self-healing disabled my script is taking 4 mins but with self-healing enabled it took 54 mins. And I am noticing it highlights all the elements even if there is no change in locators.

**Comment by GannaChernyshova** [comment]
Hi @shiva4983 
Can you please share some details of you test project(how may tests)? Does Healenium generates the report after a test run? What results are there?

**Comment by shiva4983** [comment]
Hi @GannaChernyshova , there are couple of issues, I found based on further analysis. findelement is working fine. however, while using findelements, irrespective of property change, healenium is try to heal all the object. Also, the current version of docker backend is not registering the heal report.

**Comment by Aliaksei-Ashukha** [comment]
Hi @shiva4983
Could you provide example of findElements scenario? 
And what version do you use? Note, Healenium cannot to generate report during test failure case.

**Comment by Raghuramanvaradhan** [comment]
Hi, @GannaChernyshova, @Aliaksei-Ashukha  as @shiva4983  said Execution has become too slow and it highlights the elements before performing an action, added to that I cannot get the secret key to view the report on localhost when  I run via eclipse (Maven clean and maven test). Any assistance will be highly helpful. Thanks!

**Comment by Oktaliem** [comment]
Agree with @shiva4983, I also facing this issue.
I have 83/84 test cases.
Execution time without healenium was +- 2 hours
![image](https://user-images.githubusercontent.com/26521948/127764449-89d0ffb6-d75c-4ff2-9273-1e8b7eeebf88.png)

Execution time with healenium was +- 6 hours
 ![image](https://user-images.githubusercontent.com/26521948/127764435-6e6cf149-7bf5-4fea-bf16-ee264b00bec2.png)

Some issues that might be the root cause for my case:
given  -> I have this locator:
![image](https://user-images.githubusercontent.com/26521948/127764787-92ed5601-86b6-442d-a138-8bdfac7ea041.png)
given -> I have this method: 
![image](https://user-images.githubusercontent.com/26521948/127765165-b420a4c8-16c4-4370-8b7e-f339e907cd63.png)

So likely helenium need think time/ processing time to find the correct locator?
in total (based on the report), healenium tried to heal 1048 locators. ( equal to extra 4 hours of test execution time => +- 13 seconds of processing time to find healed locator on my machine)
![image](https://user-images.githubusercontent.com/26521948/127765890-34d0e92d-aa27-42a8-9603-3c121927de76.png)


I have classified all the reports and below the main problem for my case:
1. healenium tried to heal allure report object (267 times) ?
![image](https://user-images.githubusercontent.com/26521948/127764658-3fd89498-5c8e-44c2-b9ee-655a947da9ba.png)
2. healenium tried to heal locator when I have selenium method click via javascript (542 times)? 
![image](https://user-images.githubusercontent.com/26521948/127765717-2aa01b89-96ae-4d5a-9833-72a3ad67c1e8.png)
3. healenium tried to heal click method (163 times)
![image](https://user-images.githubusercontent.com/26521948/127765688-00ceb705-311b-4544-b57b-a8b75c350916.png) 
![image](https://user-images.githubusercontent.com/26521948/127765684-e8615d63-03b3-4ce9-b52f-15888c390713.png)

I also tried to change the element based on healedLocatorValue/Type above with the assumption to reduce healenium processing time. None of them are working (random sampling)

**Comment by Aliaksei-Ashukha** [comment]
Fixed at rev. 3.2.0+
