### ISSUE TITLE
Not able to proceed further on login page

### ISSUE THREAD

**Issue by priyanka748** [healenium/healenium-web#176]
### Describe the problem

I have tried for the username nd pswd.. whn it click the submit.. at that time i get no username is provided.
![Capture](https://user-images.githubusercontent.com/49894816/155336240-89baa86a-4abc-4002-8ef6-2c4082df1af6.PNG)
PFA.

### Healenium Web version

3.1.6

### Healenium Backend version

hlm-backend:3.1.5

### Selenium version

3.141.159

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = 0.5
heal-enabled = true
serverHost = localhost
serverPort = 7878

### Logs appeared during using Healenium

```shell
Session ID: 1902417e341bf2bda85e283cb2a02698
*** Element info: {Using=id, value=password}
Trying to heal...
19:28:57.466 [main] WARN  c.e.h.s.i.AbstractHealingServiceImpl - Using healed locator: Optional[Scored(score=0.8571428571428571, value=By.id: fdfd)]
```

**Comment by ElenaStepuro** [comment]
Hello @priyanka748 Answered via e-mail)
However, I'll duplicate it here also. This exception means that this element hasn’t been ever found on a page. So, healing will be appeared only if the element has been successfully found on page at least once. Otherwise, that means that locator doesn’t correct.
So, this is not Healenium issue and I close it
