### ISSUE TITLE
[Need support]: While my application page is opening, Healenium starts healing the locators

### ISSUE THREAD

**Issue by hukkerijc** [healenium/healenium-web#214]
### Describe the problem

While my page is still loading, Healenium starts healing the locators. This results into unnecessary healing of the locators. Kindly help to how can I make sure, Healenium starts healing only when the element is not found after the page is loaded.

### Healenium Web version

3.3.0

### Healenium Backend version

3.2.5

### Selenium version

4.5.0

### Platform

Java

### Properties file

recovery-tries=20
score-cap=0.8
heal-enabled=true
serverHost=localhost
serverPort=7878
imitatePort=8000

### Logs appeared during using Healenium

```shell
Nothing specific logs, we get logs like when it is trying to heal:
Trying to heal...
[main] WARN com.epam.healenium.processor.SaveHealingResultsProcessor - Using healed locator: Scored(score=0.8685714285714285, value=By.cssSelector: html > body > div:nth-child(3) > section > div > div:nth-child(3) > div:nth-child(2) > div > div:nth-child(4) > div:nth-child(2) > div > span > div > div > div:nth-child(1) > span)
```

**Comment by raghunadh10** [comment]
Hi @ElenaStepuro  , I have been facing the same issue too as @hukkerijc  . one thing to add to the above point is , during debug mode whenever the program is stopped , healenium is not stopping and trying to heal the elements by finding them even there is no exception thrown and due to this the next steps in the scenario are not getting executed properly . can you please look into this thing. i am also using the same properties as above mentioned . Hi @hukkerijc , do you any latest update on the issue from your side ?

**Comment by Alex-Reif** [comment]
Hello @hukkerijc , @raghunadh10 , we added support Explicity Waits from hlm-web:3.4.4. You can use Explicit wait to block healing on some seconds.
